substitutions:
        _NODE_VERSION: # version for node
        _STORAGE_LOCATION: #location of bucket
        
steps:
#- name: gcr.io/$PROJECT_ID/$(_SONAR_PROJECT_PATH):latest
#  entrypoint: /bin/bash
#  args:
#    - '-c'
#    - 'if [ $BRANCH_NAME != 'production' ]; then sonar-scanner -Dsonar.host.url={$_SONAR_HOST_URL} -Dsonar.login=${_SONAR_LOGIN} -Dsonar.projectKey=${_SONAR_PROJECT_NAME} -Dsonar.sources=. ; fi'
- name: node:${_NODE_VERSION}
  entrypoint: yarn
  args: ['install']
- name: node:${_NODE_VERSION}
  entrypoint: yarn
  args: ['build']  
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/bash
  args:
    - '-c'
    - | 
        gsutil -m rm -r gs://${_STORAGE_LOCATION}/** #https://cloud.google.com/storage/docs/gsutil/commands/rm
timeout: 1200s
artifacts:
  objects:
    location: 'gs://${_STORAGE_LOCATION}/'
    paths: ['./dist/*']
#images: ['gcr.io/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME:$COMMIT_SHA']  
  