substitutions:
        _NODE_VERSION: 12.17.0 # version for node
        _STORAGE_LOCATION: #location of bucket
        
steps:
#- name: gcr.io/$PROJECT_ID/$(_SONAR_PROJECT_PATH):latest
#  entrypoint: /bin/bash
#  args:
#    - '-c'
#    - 'if [ $BRANCH_NAME != 'production' ]; then sonar-scanner -Dsonar.host.url={$_SONAR_HOST_URL} -Dsonar.login=${_SONAR_LOGIN} -Dsonar.projectKey=${_SONAR_PROJECT_NAME} -Dsonar.sources=. ; fi'
- name: node:${_NODE_VERSION}
  entrypoint: yarn
  args: ['install']
- name: node:${_NODE_VERSION}
  entrypoint: yarn
  args: ['build']  
# empty the targetted bucket if exist 
# https://cloud.google.com/storage/docs/gsutil/commands/rm
- name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rm', '-r',  'gs://${_STORAGE_LOCATION}/** || true']
timeout: 1200s

  